//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Upload
    {
        public System.Guid UploadId { get; set; }
        public string File_name { get; set; }
        public long File_size { get; set; }
        public string File_Path { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> UserRefId { get; set; }
        public string File_Type { get; set; }
    }
}
