//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int Id { get; set; }
        public int QualRefID { get; set; }
        public int EmRefID { get; set; }
    
        public virtual Employee_Master Employee_Master { get; set; }
        public virtual Qualification_Master Qualification_Master { get; set; }
    }
}
